--CREANDO LA BASE DE DATOS
CREATE DATABASE PROYECTO_FINAL

--USANDO LA BASE DE DATOS
USE PROYECTO_FINAL

--CREANDO LAS TABLAS
CREATE TABLE USUARIOS(
ID_USUARIO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NOMBRES NVARCHAR(30) NOT NULL,
APELLIDOS NVARCHAR(30) NOT NULL,
FECHA_DE_NACIMIENTO DATE NOT NULL,
TIPO_DE_USUARIO NVARCHAR(13) NOT NULL,
NOMBRE_DE_USUARIO NVARCHAR(50) NOT NULL,
CONTRASEÑA NVARCHAR(50) NOT NULL
--ESTABLECIENDO CAMPO UNICO
CONSTRAINT NOMBRE_DE_USUARIO_UNICO UNIQUE(NOMBRE_DE_USUARIO),
CONSTRAINT CONTRASEÑA_UNICA UNIQUE(CONTRASEÑA)
)

CREATE TABLE EDIFICIOS(
ID_EDIFICIO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NUMERO_DE_EDIFICIO INT NOT NULL
--ESTABLECIENDO CAMPO UNICO
CONSTRAINT NUMERO_DE_EDIFICIO_UNICO UNIQUE(NUMERO_DE_EDIFICIO)
)

CREATE TABLE SECCIONES(
ID_SECCIONES INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NOMBRE NVARCHAR(50) NOT NULL,
NUMERO_DE_EDIFICIO INT NOT NULL
--ESTABLECIENDO CAMPO UNICO
CONSTRAINT NOMBRE_UNICO UNIQUE(NOMBRE)
--ESTABLECIENDO LLAVES FORANEAS
CONSTRAINT FK_SECCIONES_NUMERO_DE_EDIFICIO FOREIGN KEY (NUMERO_DE_EDIFICIO) REFERENCES EDIFICIOS(ID_EDIFICIO)
)

CREATE TABLE VISITAS(
ID_VISITA INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NOMBRES NVARCHAR(30) NOT NULL,
APELLIDOS NVARCHAR(30) NOT NULL,
CARRERA NVARCHAR(50) NULL,
CORREO NVARCHAR(50) NULL,
EDIFICIO INT NOT NULL,
FECHA_Y_HORA_DE_ENTRADA DATETIME NOT NULL,
FECHA_Y_HORA_DE_SALIDA DATETIME NULL,
MOTIVO_DE_VISITA NVARCHAR(100) NOT NULL,
AULA_O_LUGAR_AL_QUE_SE_DIRIGE NVARCHAR(50) NOT NULL,
FOTO IMAGE NULL,
--ESTABLECIENDO LLAVES FORANEAS
CONSTRAINT FK_VISITAS_EDIFICIO FOREIGN KEY(EDIFICIO) REFERENCES EDIFICIOS(ID_EDIFICIO),
CONSTRAINT FK_VISITAS_AULA_O_LUGAR_AL_QUE_SE_DIRIGE FOREIGN KEY(AULA_O_LUGAR_AL_QUE_SE_DIRIGE) REFERENCES SECCIONES(NOMBRE)
)

--VISTAS DE TABLAS
SELECT *FROM VISITAS
SELECT *FROM USUARIOS
SELECT *FROM EDIFICIOS
SELECT *FROM SECCIONES

--ELIMINAR LAS TABLAS
DROP TABLE VISITAS
DROP TABLE USUARIOS
DROP TABLE EDIFICIOS
DROP TABLE SECCIONES

--PROCEDMIENTO INSERTAR USUARIOS
GO
CREATE PROCEDURE SP_INSERTAR_USUARIO
@NOMBRES NVARCHAR(30),
@APELLIDOS NVARCHAR(30),
@FECHA_DE_NACIMIENTO DATE,
@TIPO_DE_USUARIO NVARCHAR(13),
@NOMBRE_DE_USUARIO NVARCHAR(50),
@CONTRASEÑA NVARCHAR(50)
AS
INSERT INTO USUARIOS VALUES (@NOMBRES,@APELLIDOS,@FECHA_DE_NACIMIENTO,@TIPO_DE_USUARIO,@NOMBRE_DE_USUARIO,@CONTRASEÑA)

--PROCEDIMIENTO INSERTAR EDIFICIO
GO
CREATE PROCEDURE SP_INSERTAR_EDIFICIO
@NUMERO_DE_EDIFICIO INT,
@NOMBRE_SECCION NVARCHAR(50)
AS
INSERT INTO EDIFICIOS VALUES(@NUMERO_DE_EDIFICIO)
INSERT INTO SECCIONES VALUES(@NOMBRE_SECCION,@NUMERO_DE_EDIFICIO)

--PROCEDIMIENTO MODIFICAR EDIFICIO
GO
CREATE PROCEDURE SP_MODIFICAR_EDIFICIO
@NUMERO_DE_EDIFICIO INT,
@NOMBRE_SECCION_VIEJO NVARCHAR(50),
@NOMBRE_SECCION_NUEVO NVARCHAR(50)
AS
UPDATE SECCIONES SET NOMBRE=@NOMBRE_SECCION_NUEVO WHERE NUMERO_DE_EDIFICIO=@NUMERO_DE_EDIFICIO AND NOMBRE=@NOMBRE_SECCION_VIEJO

--PROCEDIMIENTO AGREGAR SECCION DE EDIFICIO
GO 
CREATE PROCEDURE SP_AGREGAR_SECCION
@NUMERO_DE_EDIFICIO INT,
@NOMBRE_SECCION NVARCHAR(50)
AS
INSERT INTO SECCIONES VALUES(@NOMBRE_SECCION,@NUMERO_DE_EDIFICIO)

--PROCEDIMIENTO AGREGAR VISITA
GO 
CREATE PROCEDURE SP_AGREGAR_VISITA
@NOMBRES NVARCHAR(30),
@APELLIDOS NVARCHAR(30),
@CARRERA NVARCHAR(50),
@CORREO NVARCHAR(50),
@EDIFICIO INT,
@FECHA_Y_HORA_DE_ENTRADA DATETIME,
@FECHA_Y_HORA_DE_SALIDA DATETIME,
@MOTIVO_DE_VISITA NVARCHAR(100),
@AULA_O_LUGAR_AL_QUE_SE_DIRIGE NVARCHAR(50),
@FOTO IMAGE
AS
INSERT INTO VISITAS VALUES(@NOMBRES,@APELLIDOS,@CARRERA,@CORREO,@EDIFICIO,@FECHA_Y_HORA_DE_ENTRADA,@FECHA_Y_HORA_DE_SALIDA,@MOTIVO_DE_VISITA,@AULA_O_LUGAR_AL_QUE_SE_DIRIGE,@FOTO)

--PROCEDIMIENTO ALMACENADO CONSULTAR VISITAS POR EDIFICIO
GO
CREATE PROCEDURE SP_BUSCAR_VISITAS_POR_EDIFICIO
@EDIFICIO INT
AS
SELECT *FROM VISITAS WHERE EDIFICIO = @EDIFICIO

--PROCEDIMIENTO ALMACENADO VALIDAR USUARIO ADMINISTRADOR
GO
CREATE PROCEDURE SP_VALIDAR_USUARIO
@NOMBRE_DE_USUARIO NVARCHAR(30),
--@TIPO_DE_USUARIO NVARCHAR(13),
@CONTRASEÑA NVARCHAR(50)
AS
SELECT TIPO_DE_USUARIO FROM USUARIOS WHERE NOMBRE_DE_USUARIO=@NOMBRE_DE_USUARIO AND CONTRASEÑA=@CONTRASEÑA

--PROCEDIMIENTO ALMACENADO VER EDIFICIOS
GO 
CREATE PROCEDURE SP_VER_EDIFICIOS
AS
SELECT NUMERO_DE_EDIFICIO FROM EDIFICIOS 

--PROCEDIMIENTO ALMACENADO VER SECCIONES
GO
CREATE PROCEDURE SP_VER_SECCIONES
AS
SELECT NOMBRE FROM SECCIONES

--EJECUTAR PROCEDIMIENTOS ALMACENADOS
EXEC SP_INSERTAR_USUARIO 'LUIS','PASCUAL POLANCO','1997/4/23','ADMINISTRADOR','LUIS23','654321'
EXEC SP_INSERTAR_USUARIO 'GABRIEL','BATISTA MONTILLA','1999/5/9','GENERAL','GABRIEL09','123456'
EXEC SP_INSERTAR_EDIFICIO 1,'AREA DE CAJA'
EXEC SP_MODIFICAR_EDIFICIO 1,'AREA DE COMPRA','ZONA DE FUTBOL'
EXEC SP_AGREGAR_SECCION 1,'AREA DE COMPRA'
EXEC SP_AGREGAR_VISITA 'CARLOS JAVIER','PASCUAL POLANCO','TECNOLOGO DE SOFTWARE','carlos@gmail.com',1,'2020-04-13 08:00:00','2020-04-13 12:00:00','CONSULTA','AREA DE CAJA'
EXEC SP_BUSCAR_VISITAS_POR_EDIFICIO 1
EXEC SP_VALIDAR_USUARIO 'LUIS23','654321'
EXEC SP_VER_EDIFICIOS
EXEC SP_VER_SECCIONES

--ELIMINAR PROCEDIMIENTOS ALMACENADOS
DROP PROCEDURE SP_INSERTAR_USUARIO
DROP PROCEDURE SP_INSERTAR_EDIFICIO
DROP PROCEDURE SP_MODIFICAR_EDIFICIO
DROP PROCEDURE SP_AGREGAR_SECCION
DROP PROCEDURE SP_AGREGAR_VISITA
DROP PROCEDURE SP_BUSCAR_VISITAS_POR_EDIFICIO
DROP PROCEDURE SP_VALIDAR_USUARIO
DROP PROCEDURE SP_VER_EDIFICIOS
DROP PROCEDURE SP_VER_SECCIONES

EXEC SP_BUSCAR_SECCIONES_POR_EDIFICIO 1
GO
CREATE PROCEDURE SP_BUSCAR_SECCIONES_POR_EDIFICIO
@NUMERO_DE_EDIFICIO INT
AS
SELECT NOMBRE FROM SECCIONES WHERE NUMERO_DE_EDIFICIO = @NUMERO_DE_EDIFICIO




  